# Generated by Django 3.2.20 on 2023-08-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
