# Generated by Django 3.2.20 on 2023-08-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('animals', 'Protecting animals'), ('aquatic systems', 'Protecting aquatic systems'), ('soil & trees', 'Protecting the soil & trees'), ('save resources', 'Saving resources'), ('eco-conscious diet', 'Eco-conscious diet'), ('others', 'Others')], default='others', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
