# Generated by Django 3.2.20 on 2023-08-26 08:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230826_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default image', max_length=255, verbose_name='image'),
        ),
    ]
